
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-server
  namespace: treelogy-template
  labels:
    app: angularapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: angularapi
  template:
    metadata:
      labels:
        app: angularapi
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: angularapi
        image: treelogy-template
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: angular-service
  namespace: treelogy-template
spec:
  selector:
    app: angularapi
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: treelogy-template
  name: angular-ingress
  annotations:
    allow.http: "false"
spec:
  rules:
  - host: treelogy-template.rancher.treelogy.eco.br
    http:
      paths:
        - path: /
          backend:
            serviceName: angular-service
            servicePort: 80