pipeline{
    agent any
    stages{
        stage ('Source Code'){
            steps{
                dir('code-source'){
                      git branch: 'development', credentialsId: 'treelogy-sandbox-github', url: 'https://github.com/treelogysystem/treelogy-template/'
                      script {
                      sh './hello-world npm install'
                      sh './treelogy-template/hello-world npm run build'
                  }
                 }
            }
          }
          stage ('Build Project'){
            steps{
                script {
                      sh './hello-world npm install'
                      sh './hello-world npm run build'
                  }
            }
          }
          stage('Docker Build Image') {
              steps {
                  script {
                      dockerapp = docker.build("cezarfelps/treelogy-template:${env.BUILD_ID}",
                        '-f ./deploy/Dockerfile .')
                  }
              }
          }
          stage('Docker Push Image') {
              steps {
                  script {
                          docker.withRegistry('https://registry.hub.docker.com', 'treelogy-sandbox-docker-hub') {
                          dockerapp.push('latest')
                          dockerapp.push("${env.BUILD_ID}")
                      }
                  }
              }
          }
        stage ('Deploy Kubernetes'){
          agent {
            kubernetes {
              cloud 'kubernetes'
            }
          }
          environment {
                tag_version = "${env.BUILD_ID}"
            }
            steps{
                sh 'sed -i "s/{{tag}}/$tag_version/g" deploy/deployment.yaml'
                sh 'cat deploy/deployment.yaml'
                kubernetesDeploy configs: 'deploy/deployment.yaml', kubeconfigId: 'treelogy-sandbox-kubeconfig-rancher'
            }
        }
    }
}
