properties([pipelineTriggers([[$class: 'GitHubPushTrigger']])])

pipeline{
    agent any
    stages{
          stage('Docker Build Image') {
              steps {
                  script {
                      dockerapp = docker.build("cezarfelps/treelogy-template-front:${env.BUILD_ID}",
                        '-f ./deploy/Dockerfile .')
                  }
              }
          }
          stage('Docker Push Image') {
              steps {
                  script {
                          docker.withRegistry('https://registry.hub.docker.com', 'treelogy-docker-hub') {
                          dockerapp.push('latest')
                          dockerapp.push("${env.BUILD_ID}")
                      }
                  }
              }
          }
        stage ('Deploy Kubernetes'){
          environment {
                tag = "${env.BUILD_ID}"
            }
            steps {
                withKubeConfig([credentialsId: 'kube', serverUrl: 'https://rancher.treelogy.eco.br']) {
                  sh 'sed -i "s/{{tag}}/${tag} /g" deploy/deployment.yaml'
                  sh 'cat deploy/deployment.yaml'
			      sh 'kubectl apply -f deploy/deployment.yaml'
			    }
            }
        }
    }
}
